# Use alacrity themes from https://github.com/alacritty/alacritty-theme
[general]
# dark
#import = [
#    "~/.config/alacritty/themes/themes/tokyo-night.toml"
#]

#light
import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]

[env]
TERM = "xterm-256color"
enable_rgb = "true"

[window]
title = "kuyangora"
decorations = "Full"

#opacity = 0.9
opacity = 1

padding.x = 10
#padding.y = 5

[selection]
save_to_clipboard = true

[font]
normal.family = "Hack Nerd Font Mono"
normal.style = "Regular"
bold.family = "Hack Nerd Font Mono"
bold.style = "Bold"
italic.family = "Hack Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "Hack Nerd Font Mono"
bold_italic.style = "Bold Italic"
size = 14.0

[terminal.shell]
# for linux
program = "tmux"

# for macos
# program = "/opt/homebrew/bin/tmux"
